package greendao.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.db.entity.memorandum;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig memorandumDaoConfig;

    private final memorandumDao memorandumDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        memorandumDaoConfig = daoConfigMap.get(memorandumDao.class).clone();
        memorandumDaoConfig.initIdentityScope(type);

        memorandumDao = new memorandumDao(memorandumDaoConfig, this);

        registerDao(memorandum.class, memorandumDao);
    }
    
    public void clear() {
        memorandumDaoConfig.getIdentityScope().clear();
    }

    public memorandumDao getMemorandumDao() {
        return memorandumDao;
    }

}
